/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diu.ulpgc.es.practica7paneldeslizable;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.ScrollPaneConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.highgui.HighGui;
import org.opencv.imgcodecs.Imgcodecs;

/**
 *
 * @author Jorge Santana
 */
public class Interfaz extends javax.swing.JFrame {

    private Mat imgOr;
    private BufferedImage img;
    private JFileChooser fc = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes (*.jpg, *.png)", "jpg", "png");
    private File file;
    private EstadisticasImagen est;
    private JScrollBar vBar;
    private JScrollBar hBar;
    /**
     * Creates new form Interfaz
     */
    class MiListener implements AdjustmentListener {
        
        @Override
        public void adjustmentValueChanged(AdjustmentEvent ae){
            if(img != null){
                Dimension dimension = new Dimension(img.getWidth(), img.getHeight());
                updateRGB(imgOr, jScrollPane.getViewport().getViewPosition(),
                    imageSize(dimension,jScrollPane.getViewport().getExtentSize()));
            }
        }
    } 
    
    
    
    public Interfaz() {
        initComponents();
        nu.pattern.OpenCV.loadShared();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        fc.addChoosableFileFilter(filter);

        est = new EstadisticasImagen();
        
        jScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        vBar = jScrollPane.getVerticalScrollBar();
        hBar = jScrollPane.getHorizontalScrollBar();
        vBar.addAdjustmentListener(new MiListener());
        hBar.addAdjustmentListener(new MiListener());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        lienzo1 = new diu.ulpgc.es.practica7paneldeslizable.Lienzo();
        rgbPanel = new javax.swing.JPanel();
        maxPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        maxRText = new javax.swing.JTextField();
        maxGText = new javax.swing.JTextField();
        maxBText = new javax.swing.JTextField();
        meanPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        meanRText = new javax.swing.JTextField();
        meanGText = new javax.swing.JTextField();
        meanBText = new javax.swing.JTextField();
        minPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        minRText = new javax.swing.JTextField();
        minGText = new javax.swing.JTextField();
        minBText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        imagenMenu = new javax.swing.JMenuItem();
        cerrarMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel.setBackground(new java.awt.Color(255, 153, 51));
        imagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Imagen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jScrollPane.setViewportView(lienzo1);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane)
        );

        rgbPanel.setBackground(new java.awt.Color(255, 153, 51));
        rgbPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Valores RGB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        maxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valores máximos"));

        jLabel1.setText("Rojo:");

        jLabel2.setText("Verde:");

        jLabel3.setText("Azul:");

        maxRText.setEditable(false);
        maxRText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxRTextActionPerformed(evt);
            }
        });

        maxGText.setEditable(false);

        maxBText.setEditable(false);

        javax.swing.GroupLayout maxPanelLayout = new javax.swing.GroupLayout(maxPanel);
        maxPanel.setLayout(maxPanelLayout);
        maxPanelLayout.setHorizontalGroup(
            maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maxPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maxRText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(maxPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maxBText))
                    .addGroup(maxPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maxGText)))
                .addContainerGap())
        );
        maxPanelLayout.setVerticalGroup(
            maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maxRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(maxGText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        meanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valores promedios"));

        jLabel4.setText("Rojo:");

        jLabel5.setText("Verde:");

        jLabel6.setText("Azul:");

        meanRText.setEditable(false);
        meanRText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meanRTextActionPerformed(evt);
            }
        });

        meanGText.setEditable(false);

        meanBText.setEditable(false);

        javax.swing.GroupLayout meanPanelLayout = new javax.swing.GroupLayout(meanPanel);
        meanPanel.setLayout(meanPanelLayout);
        meanPanelLayout.setHorizontalGroup(
            meanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(meanBText))
                    .addGroup(meanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(meanRText))
                    .addGroup(meanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(meanGText)))
                .addContainerGap())
        );
        meanPanelLayout.setVerticalGroup(
            meanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(meanRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(meanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(meanGText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(meanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(meanBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        minPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valores mínimos"));

        jLabel7.setText("Rojo:");

        jLabel8.setText("Verde:");

        jLabel9.setText("Azul:");

        minRText.setEditable(false);
        minRText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRTextActionPerformed(evt);
            }
        });

        minGText.setEditable(false);

        minBText.setEditable(false);

        javax.swing.GroupLayout minPanelLayout = new javax.swing.GroupLayout(minPanel);
        minPanel.setLayout(minPanelLayout);
        minPanelLayout.setHorizontalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(minPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minRText))
                    .addGroup(minPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minBText))
                    .addGroup(minPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minGText)))
                .addContainerGap())
        );
        minPanelLayout.setVerticalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(minRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(minGText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(minBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel10.setText("Jorge Santana Lorenzo");

        jLabel11.setText("Francisco Javier Sánchez González");

        javax.swing.GroupLayout rgbPanelLayout = new javax.swing.GroupLayout(rgbPanel);
        rgbPanel.setLayout(rgbPanelLayout);
        rgbPanelLayout.setHorizontalGroup(
            rgbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rgbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rgbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rgbPanelLayout.createSequentialGroup()
                        .addGroup(rgbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rgbPanelLayout.setVerticalGroup(
            rgbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rgbPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(maxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(meanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        archivoMenu.setText("Archivo");

        imagenMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        imagenMenu.setText("Abrir Imagen");
        imagenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenMenuActionPerformed(evt);
            }
        });
        archivoMenu.add(imagenMenu);

        cerrarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cerrarMenu.setText("Cerrar Aplicación");
        cerrarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMenuActionPerformed(evt);
            }
        });
        archivoMenu.add(cerrarMenu);

        jMenuBar1.add(archivoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rgbPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rgbPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maxRTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxRTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxRTextActionPerformed

    private void meanRTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meanRTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meanRTextActionPerformed

    private void minRTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minRTextActionPerformed

    private void imagenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenMenuActionPerformed
        int op = fc.showOpenDialog(this);
        if(op == JFileChooser.APPROVE_OPTION) {
            if(file.getName().endsWith(".jpg") || file.getName().endsWith(".png")) {
                file = fc.getSelectedFile();
                updateScrollPane();
                imgOr = Imgcodecs.imread(file.getPath());
                img = (BufferedImage) HighGui.toBufferedImage(imgOr);
                lienzo1.setImage(img);
                updateRGB(imgOr, jScrollPane.getViewport().getViewPosition(), imageSize(new Dimension(img.getWidth(),img.getHeight()),jScrollPane.getViewport().getExtentSize()));
            } else {
                JOptionPane.showMessageDialog(this, "Sólo se pueden abrir archivos con extensión .jpg o .png");
            }
        }
    }//GEN-LAST:event_imagenMenuActionPerformed

    private void cerrarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMenuActionPerformed
       int res = JOptionPane.showConfirmDialog(this, "¿Desea cerrar la aplicación?", "Cerrar aplicación", JOptionPane.YES_NO_OPTION);
       if(res == JOptionPane.YES_OPTION) {
           dispose();
       }
    }//GEN-LAST:event_cerrarMenuActionPerformed
    
    
    
    public Dimension imageSize(Dimension imgSize, Dimension scrollSize) {
        if(imgSize.width< scrollSize.width){
            if(imgSize.height < scrollSize.height){
                return imgSize;
            }else{
                return new Dimension(imgSize.width, scrollSize.height);
            }
        }else if(imgSize.height < scrollSize.height){
            return new Dimension(scrollSize.width, imgSize.height);
        }
        return scrollSize;        
    }
    
    private void updateRGB(Mat imagen, Point esquinaSI, Dimension dimension) {
       est.calculaEstadisticas(imagen, esquinaSI, dimension);
       int[] maxRGB = est.getMaximo();
       int[] meanRGB = est.getPromedio();
       int[] minRGB = est.getMinimo();
       
       maxRText.setText(""+ maxRGB[est.ROJO]);
       meanRText.setText(""+ meanRGB[est.ROJO]);       
       minRText.setText(""+ minRGB[est.ROJO]);
       
       maxGText.setText(""+ maxRGB[est.VERDE]);
       meanGText.setText(""+ meanRGB[est.VERDE]);
       minGText.setText(""+ minRGB[est.VERDE]);
       
       maxBText.setText(""+ maxRGB[est.AZUL]);
       meanBText.setText(""+ meanRGB[est.AZUL]);
       minBText.setText(""+ minRGB[est.AZUL]);
       
    }

    private void updateScrollPane() {
       vBar.setValue(0);
       hBar.setValue(0);
       jScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
       jScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
       jScrollPane.repaint();
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenuItem cerrarMenu;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JMenuItem imagenMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane;
    private diu.ulpgc.es.practica7paneldeslizable.Lienzo lienzo1;
    private javax.swing.JTextField maxBText;
    private javax.swing.JTextField maxGText;
    private javax.swing.JPanel maxPanel;
    private javax.swing.JTextField maxRText;
    private javax.swing.JTextField meanBText;
    private javax.swing.JTextField meanGText;
    private javax.swing.JPanel meanPanel;
    private javax.swing.JTextField meanRText;
    private javax.swing.JTextField minBText;
    private javax.swing.JTextField minGText;
    private javax.swing.JPanel minPanel;
    private javax.swing.JTextField minRText;
    private javax.swing.JPanel rgbPanel;
    // End of variables declaration//GEN-END:variables
}
